// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZhUt3QV_VFEEGcJJxp4u1Gi2CZnpgNw',
    appId: '1:44382695843:web:722d5923154f9304cbea16',
    messagingSenderId: '44382695843',
    projectId: 'newsfeed-5e22a',
    authDomain: 'newsfeed-5e22a.firebaseapp.com',
    storageBucket: 'newsfeed-5e22a.appspot.com',
    measurementId: 'G-V91JRCJ6C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRZ2Z2iaaYs1mXU1EZTyNn_13XcQskkCM',
    appId: '1:44382695843:android:22ce0fa6bac879d1cbea16',
    messagingSenderId: '44382695843',
    projectId: 'newsfeed-5e22a',
    storageBucket: 'newsfeed-5e22a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBSsRdiec_IoxFMyfjvORpR0VmFWio1U',
    appId: '1:44382695843:ios:93d04e71c86ce1facbea16',
    messagingSenderId: '44382695843',
    projectId: 'newsfeed-5e22a',
    storageBucket: 'newsfeed-5e22a.appspot.com',
    iosBundleId: 'com.newsfeed.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBSsRdiec_IoxFMyfjvORpR0VmFWio1U',
    appId: '1:44382695843:ios:3cfd2b67a3f0e66acbea16',
    messagingSenderId: '44382695843',
    projectId: 'newsfeed-5e22a',
    storageBucket: 'newsfeed-5e22a.appspot.com',
    iosBundleId: 'com.android.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgZhUt3QV_VFEEGcJJxp4u1Gi2CZnpgNw',
    appId: '1:44382695843:web:621ec6f39a517e0fcbea16',
    messagingSenderId: '44382695843',
    projectId: 'newsfeed-5e22a',
    authDomain: 'newsfeed-5e22a.firebaseapp.com',
    storageBucket: 'newsfeed-5e22a.appspot.com',
    measurementId: 'G-2H4LSZHX88',
  );
}
